// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeHeaderCommentGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeHeaderCommentGenerator.1713d542-ba6d-4425-80ec-e4952467a258";
        public const string Name = "CodeHeaderCommentGenerator";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "HP";
        public const string Tags = "";
    }
}
